// Short parenthetical glosses for restricted needs vocabulary (Belief Mastery Ch.5)
// Keys are lowercase; match NEEDS_VOCABULARY token spellings.

export const NEED_GLOSS = {
  acceptance: 'being received without having to earn worth',
  affection: 'warmth and care expressed physically or emotionally',
  appreciation: 'being valued for who you are or what you offer',
  belonging: 'feeling part of a group or place where you fit',
  cooperation: 'working together toward shared aims',
  communication: 'exchange that lands and is understood',
  closeness: 'emotional nearness without losing self',
  community: 'shared context with mutual recognition',
  companionship: 'steady company that eases aloneness',
  compassion: 'being met with kindness when you suffer',
  consideration: 'your reality factored in by others',
  consistency: 'predictable enough responsiveness to relax',
  empathy: 'someone feeling with you, not just for you',
  inclusion: 'being brought in rather than left outside',
  intimacy: 'known-ness and vulnerability held safely',
  love: 'deep care, commitment, or cherishing',
  mutuality: 'give-and-take rather than one-way taking',
  nurturing: 'being tended to so you can grow or heal',
  respect: 'being regarded with dignity',
  'self-respect': 'holding your own worth inwardly',
  safety: 'freedom from threat; enough protection to soften',
  security: 'stable enough ground under you',
  stability: 'life rhythms you can count on',
  support: 'backup when strain or doubt hits',
  'to know and be known': 'truth of you seen and met',
  'to see and be seen': 'witnessed as real, not overlooked',
  'to understand and be understood': 'sense-making shared both ways',
  trust: 'reliability of care, word, or outcome',
  warmth: 'human tenderness you can feel',

  movement: 'body in motion; discharge and vitality',
  exercise: 'structured physical exertion for body/mind',
  sleep: 'restorative unconscious down-time',
  'sexual expression': 'erotic aliveness expressed consensually',
  'safe-space': 'environment where you can regulate',
  shelter: 'physical cover and basic refuge',
  touch: 'contact that regulates or connects',
  air: 'breathable, sufficient atmosphere',
  food: 'nourishment that grounds energy',
  flow: 'smooth continuity without constant friction',
  nutrition: 'what the body uses to repair and run',
  nourishment: 'being fed in body or soul',
  rest: 'pause that restores capacity',
  flexibility: 'adaptability without snapping',
  adaptability: 'adjusting to change without collapse',
  hydration: 'fluid balance for body function',
  elimination: 'letting go of waste or tension',
  clearing: 'space made by release or completion',
  growth: 'development, expansion, or maturation',
  progress: 'forward motion you can notice',
  elemental: 'contact with raw life forces (earth, weather, body)',

  authenticity: 'alignment between inner truth and outer expression',
  integrity: 'wholeness; words and actions match values',
  presence: 'here-and-now awareness without fleeing inward',
  joy: 'lifted aliveness or delight',
  humor: 'playful perspective that lightens weight',
  fun: 'light engagement without heavy stakes',
  adventure: 'novelty, risk, or exploration that enlivens',

  beauty: 'aesthetic or soul resonance that uplifts',
  communion: 'felt union beyond separate selves',
  ease: 'relief from chronic strain or vigilance',
  equality: 'parity of standing, voice, or weight',
  harmony: 'parts working together without inner war',
  inspiration: 'being moved toward meaning or creation',
  order: 'structure that reduces chaos or overload',

  choice: 'real options you can exercise',
  freedom: 'room to move, speak, or decide',
  independence: 'self-direction without undue reliance',
  space: 'room physically, emotionally, or mentally',
  spontaneity: 'unscripted aliveness or impulse',

  awareness: 'conscious noticing without denial',
  'celebration of life': 'honoring aliveness and passage',
  challenge: 'stretch that builds without breaking',
  clarity: 'cognitive or emotional sharpness about what is true',
  competence: 'capability you trust in a domain',
  consciousness: 'awake relation to inner and outer',
  contribution: 'impact or gift that lands outward',
  creativity: 'making something new or rearranging meaning',
  discovery: 'finding what was unknown',
  efficacy: 'sense that effort produces effect',
  effectiveness: 'outcomes matching intention',
  hope: 'forward-facing possibility you can lean on',
  learning: 'taking in skill or understanding',
  mourning: 'grieving loss so it can move through',
  participation: 'having a place in what unfolds',
  purpose: 'direction that organizes effort',
  'self-expression': 'outward shape of inner truth',
  stimulation: 'arousal, novelty, or intensity that engages',
  'to matter': 'significance; that your being or doing counts',
  understanding: 'grasp of meaning, cause, or context',
  'safe space': 'context where risk feels containable',
  'being liked': 'positive regard from others',
  'being esteemed': 'respect or admiration from others',
  approval: 'validation that you are acceptable',
  'being wanted': 'desired rather than merely tolerated',
  'being right': 'correctness or moral standing affirmed',
  'being loved': 'deep cherishing from another',
  'trust in something greater than self': 'faith or orientation beyond the personal ego'
};
