// Practical actions for addressing loop need and root need
// Used by Dependency Loop Tracer Action Strategies
// Keys match need text (case-insensitive lookup); fallback by category

const titleCase = (s) => String(s || '').replace(/\b\w/g, c => c.toUpperCase()).trim();

export const NEED_LOOP_ACTIONS = {
  'Acceptance': ['Pause before seeking validation; ask "Do I need this response to feel OK?"', 'Notice when you change yourself to fit in; choose one situation to show up as you are', 'Reduce people-pleasing by saying no to one low-stakes request daily', 'Identify one person whose approval you can release dependence on'],
  'Affection': ['Notice when you seek touch or closeness to fill a void; pause and breathe', 'Create non-dependent ways to receive warmth (self-care, pets, nature)', 'Set a boundary: one interaction per day where you give affection without expecting return', 'Track compulsive intimacy-seeking; introduce a delay before acting'],
  'Appreciation': ['Stop overworking for acknowledgment; do one invisible act of contribution', 'Notice when you downplay achievements; practice stating one win without apology', 'Reduce dependence on external praise by writing one self-acknowledgment daily', 'Identify situations where you seek recognition and add a pause'],
  'Belonging': ['Notice sacrificing individuality for acceptance; reclaim one preference or boundary', 'Reduce group-hopping; commit to one community or relationship more deeply', 'Practice belonging without merging: attend one gathering as yourself, not as chameleon', 'Create solo rituals that affirm "I belong to myself"'],
  'Autonomy': ['Make one small decision daily without seeking permission or validation', 'Set a boundary: protect 15–30 min of unscheduled time for yourself', 'Notice when you over-commit to avoid freedom; decline one request', 'Identify one area where you defer to others and take the lead'],
  'Connection': ['Reduce over-sharing; share one thing and sit with the silence', 'Notice avoidance of intimacy; initiate one low-stakes connection', 'Create connection that doesn\'t drain: one quality interaction without expectation', 'Practice receiving without reciprocating immediately'],
  'Safety': ['Identify one situation where safety-seeking limits your life; take a small calculated risk', 'Notice hypervigilance; practice grounding (feet on floor, breath) before reacting', 'Reduce avoidance by entering one feared-but-safe situation', 'Create internal safety through routine: one predictable daily anchor'],
  'Approval': ['Delay seeking approval; act first, then notice the urge to check in', 'Identify whose approval matters most; practice one action without their validation', 'Notice approval-seeking in conversation; reduce by 50% one day', 'Write down one thing you did well without telling anyone'],
  'Control': ['Release one small thing you control; observe what happens', 'Notice when control masks fear; name the fear and sit with it', 'Reduce over-planning: allow one 30-min block to be unstructured', 'Practice asking for help instead of doing it yourself'],
  'Security': ['Identify one way you over-secure (money, relationships, routines); loosen slightly', 'Notice when security-seeking prevents growth; take one small step into uncertainty', 'Create security from within: one daily practice that grounds you', 'Reduce checking behaviors; set a limit (e.g. check bank once per day)'],
  'Validation': ['Pause before sharing to get a reaction; ask "Am I sharing to connect or to be validated?"', 'Notice when you need others to confirm your worth; write one self-validation', 'Reduce social-media validation-seeking; post one thing without checking likes', 'Identify one arena where you depend on external validation; meet it yourself first'],
  'Love': ['Notice when you seek love to fill a void; practice loving yourself in that moment', 'Reduce conditional giving: give one act of love without expectation of return', 'Create non-dependent love: care for someone without needing them to need you', 'Practice receiving love without deflecting or minimizing'],
  'Support': ['Identify one thing you always ask others to do; try doing it yourself or finding another way', 'Notice when you seek support to avoid discomfort; sit with the discomfort once', 'Reduce over-reliance: solve one small problem without consulting anyone', 'Build self-support: one resource or skill that reduces dependence'],
  'Purpose': ['Notice when purpose-seeking becomes escapism; ground in one mundane task', 'Reduce the need for grand purpose; find meaning in one small action today', 'Identify when you chase purpose externally; ask "What would purpose look like from within?"', 'Practice purpose without performance: do one meaningful thing without sharing'],
  'Certainty': ['Tolerate one moment of uncertainty without resolving it immediately', 'Notice when you seek certainty to reduce anxiety; breathe and stay', 'Reduce over-researching; make one small decision with incomplete information', 'Practice "good enough" instead of "certain" in one area'],
  'Competence': ['Notice perfectionism; complete one task at 80% and let it go', 'Reduce over-working to prove yourself; do one thing without showing anyone', 'Identify when you avoid challenges; take one small step into discomfort', 'Practice receiving feedback without collapsing or defending'],
  'Independence': ['Notice when you refuse help to prove independence; accept one offer', 'Reduce isolation; reach out to one person without it being transactional', 'Identify when independence masks fear of reliance; experiment with healthy dependence', 'Practice interdependence: ask for one thing you could do yourself'],
  'Freedom': ['Notice when you resist authority reflexively; choose one instance of constructive compliance', 'Reduce over-commitment that kills freedom; clear one obligation', 'Identify what freedom would look like; take one concrete step toward it', 'Practice freedom within constraint: find one way to choose within limits'],
  'Rest': ['Notice when you cannot rest; schedule one non-negotiable rest block', 'Reduce guilt about resting; take 15 min without productivity', 'Identify what prevents rest; address one barrier', 'Practice rest as authorship: choose how you restore'],
  'Space': ['Claim one physical or temporal space as yours; defend it', 'Notice when you give away all your space; reclaim 30 min', 'Reduce people-pleasing that invades space; say no to one request', 'Create a ritual that marks "my space" (corner, walk, door closed)'],
  'Acceptance': ['Pause before seeking validation; ask "Do I need this response to feel OK?"', 'Notice when you change yourself to fit in; choose one situation to show up as you are', 'Reduce people-pleasing by saying no to one low-stakes request daily', 'Identify one person whose approval you can release dependence on'],
  'Intimacy': ['Slow down emotional disclosure; share one thing and let it land before sharing more', 'Notice when you create distance to feel safe; stay in one uncomfortable moment of closeness', 'Communicate your closeness needs directly rather than testing people to see if they notice', 'Set a boundary: one interaction where you give without needing deep connection in return'],
  'Trust': ['Notice when you trust blindly or withhold trust entirely; introduce a graduated step', 'Before extending full trust, observe consistency across three separate situations', 'Reduce hyper-vigilance in one safe relationship; act as though trust is present', 'When trust is broken, name it clearly rather than suppressing it or ending all contact'],
  'Love': ['Notice when you seek love to fill a void; pause and ask what you actually need right now', 'Practice receiving love without deflecting — accept one expression of care fully today', 'Give one act of love without any expectation of a return', 'Identify one way you push love away; hold still in that moment instead'],
  'Warmth': ['Seek one non-dependent source of warmth today — sunlight, a warm drink, an animal', 'Notice when you withhold warmth reflexively; offer one small gesture of care', 'Create a daily self-warmth ritual: something gentle and kind toward your own body', 'In one interaction, let warmth land without immediately deflecting it'],
  'Closeness': ['Notice when you merge — take one hour to exist independently of those you love', 'Notice when you create distance — stay in one moment of closeness without withdrawing', 'Communicate your closeness need rather than acting it out through behaviour', 'Identify one relationship where closeness can be practised safely; invest in it'],
  'Safety': ['Ground yourself physically when hypervigilance spikes: feet on floor, slow breath', 'Identify one situation where safety-seeking limits your life; take one small calculated step', 'Reduce checking behaviours by 50% in one area for one day', 'Create one internal safety anchor: a phrase, breath, or memory that reliably settles you'],
  'Touch': ['Notice when you seek touch to regulate emotion rather than connect; pause and breathe', 'If you avoid touch, allow one brief, consensual physical contact today', 'Create non-dependent sources of physical comfort: warmth, texture, gentle self-touch', 'Communicate your touch needs clearly rather than hoping others will intuit them'],
  'Movement': ['Notice when exercise is punishment or escape; choose one session that is genuinely restorative', 'If you avoid movement, commit to 10 minutes of gentle physical activity today', 'Reconnect movement to pleasure: one activity that feels good in your body rather than productive', 'Notice when you use physical activity to avoid emotional discomfort; stay with the feeling instead'],
  'Authenticity': ['Identify one small way you perform rather than exist — drop it in one interaction', 'Notice when you self-censor; share one true thought or feeling without a disclaimer', 'Reduce blunt over-disclosure; before speaking, ask "Is this mine to share right now?"', 'Practice "showing up as is" in one low-stakes situation today'],
  'Presence': ['Set aside five minutes of intentional stillness — no screens, no tasks, nothing to do', 'Notice when you drift into past or future; gently return your attention to right now', 'Reduce one distraction or avoidance habit for two hours today', 'Engage one of your senses fully for 60 seconds: what do you hear, feel, smell right now?'],
  'Order': ['Identify one area of your environment that is causing you distress; organise only that', 'Notice when the drive for order is anxiety speaking; allow one small thing to remain imperfect', 'Reduce rigidity by leaving one daily slot genuinely unplanned', 'When disorder triggers you, breathe before reorganising — act consciously, not compulsively'],
  'Harmony': ['Name one thing you are suppressing to keep the peace; write it down, even if you do not share it', 'Practise one small, direct disagreement in a safe relationship', 'Notice when you smooth over conflict and choose to stay with the discomfort for 60 more seconds', 'Identify one relationship where harmony is maintained through avoidance; address one real issue'],
  'Freedom': ['Identify one commitment you resent; either renegotiate it or choose it consciously', 'Notice when you resist rules reflexively; ask "Is this actually limiting me or is this my fear?"', 'Reduce compulsive commitments: decline one request that conflicts with your actual priorities', 'Find one way to exercise freedom within your current constraints today'],
  'Spontaneity': ['Leave one block of time this week deliberately unscheduled', 'Notice when you over-plan as a way to manage anxiety; allow one decision to be made in the moment', 'Say yes to one unplanned invitation that does not compromise your core responsibilities', 'Identify whether novelty-seeking is energy or avoidance; act accordingly'],
  'Purpose': ['Notice when purpose-seeking is escapism; ground one action in the mundane and immediate', 'Do one meaningful thing today without sharing it or seeking recognition for it', 'Ask "What would purpose look like from within?" — identify one internal answer', 'Reduce grand-purpose fixation; find one small act that connects to what actually matters to you'],
  'Self-Expression': ['Share one honest opinion or feeling today without qualifying it into nothing', 'If you over-share, practise saying one thing and sitting with the silence', 'Create something — write, draw, speak — without an audience today', 'Notice when self-expression is performance; ask "Am I expressing myself or seeking a reaction?"'],
  'To Matter': ['Do one thing today that genuinely serves another person without making it about you', 'Notice when you shrink to stay safe; take up appropriate space in one interaction', 'Identify one area where you matter right now — not from achievement, but from presence', 'When the feeling "I do not matter" arrives, pause and name it rather than act on it'],
  'Clarity': ['Notice when analysis is avoidance; make one small decision with incomplete information', 'Spend five minutes writing freely about what is actually unclear — often this resolves it', 'Reduce over-researching: set a time limit before deciding', 'When confusion arises, ask "What do I actually feel?" before asking "What do I know?"'],
  'Growth': ['Identify whether you are growing toward something or running from something; adjust accordingly', 'Allow one thing to be good enough without optimising it further', 'Engage with one challenge purely for the experience, not for what it will make you', 'When stagnation is the pattern, take one tiny step into any form of learning or challenge today'],
  'Creativity': ['Create something today purely for yourself — not to share, not to finish, just to make', 'Notice when creative block is self-protection; begin one project for 15 minutes without judgment', 'Reduce compulsive output by sitting with one unfinished piece rather than starting another', 'Identify what the work is avoiding — often the block is guarding you from something real']
};

export const NEED_ROOT_ACTIONS = {
  'Acceptance': ['Build self-acceptance practice: daily affirmation or mirror work', 'Create relationships where you can be yourself without performing', 'Develop internal acceptance before seeking it externally', 'Reduce environments that demand you change to belong'],
  'Affection': ['Schedule regular self-nurturing: massage, warmth, gentle touch (self or trusted other)', 'Build affection into daily life: hug a tree, hold a cup of tea, pet an animal', 'Create non-romantic sources of warmth: friends, family, community', 'Develop capacity to receive; practice receiving one compliment fully'],
  'Appreciation': ['Build self-appreciation ritual: end each day with three things you did well', 'Create work or contribution that aligns with your values (intrinsic reward)', 'Reduce dependence on external milestones; find satisfaction in process', 'Develop appreciation for yourself independent of output'],
  'Belonging': ['Choose one community that aligns with your values; show up consistently', 'Create belonging through contribution: give before you take', 'Build relationships where you can be fully yourself', 'Develop "belonging to self" through identity work and boundaries'],
  'Autonomy': ['Audit your life: where are you giving away choice? Reclaim one area', 'Build decision-making muscle: make small choices without consulting', 'Create financial, emotional, or practical buffers that increase independence', 'Develop clarity on your values so choices come from within'],
  'Connection': ['Schedule regular quality time with people who see you', 'Create connection rituals: weekly call, monthly meal, annual retreat', 'Build depth in fewer relationships rather than breadth in many', 'Develop capacity for solitude so connection is chosen, not needed'],
  'Safety': ['Create physical and emotional safety through routine and environment', 'Build resources: savings, skills, support network', 'Address past trauma or anxiety with professional support if needed', 'Develop internal safety through grounding, breathwork, and self-regulation'],
  'Approval': ['Reduce time with people whose approval you depend on; or change the dynamic', 'Build self-trust: keep small promises to yourself daily', 'Create work or identity that doesn\'t depend on others\' opinions', 'Develop intrinsic validation through values alignment'],
  'Control': ['Identify what you can control (your response) vs. what you cannot; release the latter', 'Build adaptability: practice responding to change without over-planning', 'Create systems that reduce need for micromanagement', 'Develop trust in process; allow outcomes to unfold'],
  'Security': ['Build financial security: emergency fund, reduce debt, diversify income', 'Create relational security: repair trust, set clear expectations', 'Develop internal security through self-reliance and competence', 'Address existential insecurity through meaning-making or spiritual practice'],
  'Validation': ['Build self-validation: journal, therapy, or coaching that strengthens inner voice', 'Create work or art that satisfies you regardless of audience', 'Reduce exposure to validation-seeking environments (e.g. social media)', 'Develop intrinsic worth through values-based living'],
  'Love': ['Build self-love practice: compassion, boundaries, self-care', 'Create loving relationships that are mutual and sustainable', 'Develop capacity to give and receive love without fusion', 'Address blocks to receiving love (therapy, inner work)'],
  'Support': ['Build support network: identify 2–3 people you can rely on', 'Develop skills that reduce dependence: learn, practice, get coaching', 'Create systems: automation, routines, delegation', 'Address the belief that needing support is weakness'],
  'Purpose': ['Clarify values and purpose through reflection or guided process', 'Create daily alignment: one action that connects to larger meaning', 'Build purpose from within rather than role or title', 'Develop tolerance for purpose that evolves; don\'t freeze it'],
  'Certainty': ['Build tolerance for uncertainty through exposure and practice', 'Create anchors: routines, relationships, beliefs that ground you', 'Develop "good enough" decision-making; reduce analysis paralysis', 'Address anxiety or control issues with professional support'],
  'Competence': ['Invest in skill-building: courses, practice, feedback', 'Create environments where you can grow without constant evaluation', 'Develop growth mindset: mistakes as learning', 'Address imposter syndrome or perfectionism with support'],
  'Independence': ['Build practical independence: skills, finances, decision-making', 'Create healthy interdependence: give and receive without fusion', 'Develop comfort with both autonomy and connection', 'Address fear of dependence or engulfment'],
  'Freedom': ['Audit commitments; release what doesn\'t serve', 'Create buffers: time, money, space that allow choice', 'Build capacity to say no without guilt', 'Develop freedom as internal state, not only external conditions'],
  'Rest': ['Schedule rest as non-negotiable; treat it like an appointment', 'Create restful environment: sleep hygiene, calm space, boundaries', 'Address beliefs that rest is laziness or waste', 'Develop rest as authorship: you choose how you restore'],
  'Space': ['Create physical space: room, corner, or ritual that is yours', 'Build temporal space: unscheduled time, boundaries on availability', 'Develop emotional space: capacity to be with yourself', 'Address enmeshment or over-giving; reclaim your margin'],
  'Acceptance': ['Build self-acceptance practice: daily affirmation or mirror work', 'Create relationships where you can be yourself without performing', 'Develop internal acceptance before seeking it externally', 'Reduce environments that demand you change to belong'],
  'Intimacy': ['Invest in one relationship with the patience to let true closeness develop over time', 'Work through the fear of being known by exploring it in therapy or trusted conversation', 'Build intimacy with yourself first: journal, reflection, solitude', 'Practise vulnerability in graduated steps rather than all at once'],
  'Trust': ['Build one relationship on demonstrated consistency rather than assumed loyalty', 'Develop trust in yourself — keep small promises to yourself daily', 'Address the root of distrust (therapy, inner work) rather than managing it forever', 'Create criteria for trust that are based on behaviour over time, not hope'],
  'Love': ['Build self-love practice: compassion, boundaries, regular self-care', 'Create relationships where love is mutual, chosen, and sustainable', 'Develop capacity to give and receive love without losing yourself', 'Address the blocks to receiving love through inner work or professional support'],
  'Warmth': ['Schedule regular warmth in your life: people, environments, rituals that feel safe and kind', 'Address the early environments that made warmth feel conditional or dangerous', 'Develop the capacity to extend warmth to yourself without needing another person present', 'Create friendships where warmth is a baseline, not a transaction'],
  'Closeness': ['Build one relationship with clear, mutual agreements about closeness and space', 'Develop a relationship with yourself so closeness with others is chosen, not needed', 'Address fear of loss or abandonment — often what drives the closeness loop — with professional support', 'Practise separateness within connection: maintain your own perspective in close relationships'],
  'Safety': ['Build internal safety through grounding practices, breathwork, and self-regulation', 'Create physical and environmental stability: routine, reliable space, consistent relationships', 'Address past trauma or threat environments with professional support', 'Develop resources — financial, social, practical — that expand your real-world safety margin'],
  'Touch': ['Schedule consensual, meaningful physical contact regularly — friends, family, bodywork', 'Develop a comfortable relationship with your own body through gentle self-care', 'Address early touch deprivation or violation with somatic or body-oriented therapy if needed', 'Create non-sexual sources of nurturing physical connection in your life'],
  'Movement': ['Create a sustainable movement practice that genuinely serves your body and mood', 'Address the emotional relationship to your body — not just the physical habits', 'Build movement as pleasure rather than punishment: prioritise what feels good', 'Investigate what you are avoiding in stillness; movement without presence is just running'],
  'Authenticity': ['Build one relationship where you can be fully yourself without editing', 'Develop a clearer sense of what you actually think and feel before sharing it', 'Address the early conditioning that made authentic expression unsafe', 'Practice integrity: say what you mean and mean what you say, in graduated steps'],
  'Presence': ['Develop a regular stillness practice: meditation, breathwork, time in nature', 'Reduce structural distraction: remove notifications, create phone-free zones', 'Address what you are avoiding in the present — often this is grief, fear, or unfelt emotion', 'Build presence as a skill by gradually extending your capacity to sit with what is'],
  'Order': ['Build systems and routines that create genuine order without requiring control of everything', 'Develop tolerance for imperfection through deliberate exposure', 'Address the underlying anxiety that order is managing — it rarely solves it', 'Create predictable anchors in your life so not everything needs to be controlled'],
  'Harmony': ['Build conflict resolution skills — most people avoid conflict because they were never taught to do it well', 'Develop the capacity to hold difficult feelings without immediately trying to smooth them', 'Create relationships where honesty is safe and disagreement does not mean destruction', 'Address the early conditioning where conflict equalled danger'],
  'Freedom': ['Audit your life for genuine versus self-imposed constraints; release what you actually can', 'Build financial, emotional, and practical independence that expands real freedom', 'Develop the capacity to be free within commitment rather than from it', 'Address fear of engulfment or control — freedom loops are often attachment wounds'],
  'Spontaneity': ['Develop a baseline of stability and safety so spontaneity feels exciting rather than threatening', 'Build genuine flexibility through small experiments with unstructured time', 'Address the early unpredictability that made spontaneity feel dangerous', 'Find routine that is chosen rather than compulsive — it creates the ground from which spontaneity is safe'],
  'Purpose': ['Clarify your actual values — purpose that is aligned with who you are does not require performance', 'Build purpose from the inside: small daily actions that connect to meaning', 'Develop tolerance for purpose that evolves; do not freeze it into an identity', 'Address the wound that made you believe your value is contingent on your contribution'],
  'Self-Expression': ['Build environments and relationships where your voice is genuinely welcomed', 'Develop the creative or expressive practice that most accurately reflects your inner life', 'Address the early silencing that made expression feel dangerous or invisible', 'Create work or output that satisfies you regardless of audience response'],
  'To Matter': ['Build a sense of inherent worth that exists independently of what you produce or provide', 'Invest in relationships where you are valued for being, not doing', 'Address the early conditioning that made mattering contingent on performance', 'Develop contribution that is given freely rather than deployed to prove significance'],
  'Clarity': ['Build a reflective practice that gives you access to your own thinking without endless loops', 'Develop tolerance for uncertainty through graduated exposure', 'Address the anxiety that clarity is managing — often it needs to be felt, not solved', 'Create decision-making frameworks that work with incomplete information'],
  'Growth': ['Develop a growth orientation rooted in genuine curiosity rather than self-repair', 'Address the belief that you are fundamentally not enough as you are', 'Build relationships and environments where growth is welcomed but not required for love', 'Find what you are running from — growth that is motivated by fear does not heal the wound'],
  'Creativity': ['Build a creative practice that exists for you, independent of output or audience', 'Address the early dismissal or punishment of your creative expression', 'Develop the courage to make imperfect work and share it selectively', 'Create conditions — time, space, safety — that allow creative expression to feel natural rather than forced']
};

// Map need text to closest key (case-insensitive, partial match)
function findBestMatch(needText, keys) {
  const n = String(needText || '').trim().toLowerCase();
  if (!n) return null;
  // Exact match first
  let key = keys.find(k => k.toLowerCase() === n);
  if (key) return key;
  // Need contains key
  key = keys.find(k => n.includes(k.toLowerCase()));
  if (key) return key;
  // Key contains need (for short needs)
  key = keys.find(k => k.toLowerCase().includes(n));
  return key || null;
}

export function getLoopActionsForNeed(needText) {
  const keys = Object.keys(NEED_LOOP_ACTIONS);
  const key = findBestMatch(needText, keys);
  return NEED_LOOP_ACTIONS[key] || NEED_LOOP_ACTIONS['Acceptance'];
}

export function getRootActionsForNeed(needText) {
  const keys = Object.keys(NEED_ROOT_ACTIONS);
  const key = findBestMatch(needText, keys);
  return NEED_ROOT_ACTIONS[key] || NEED_ROOT_ACTIONS['Acceptance'];
}
